# Generated by Django 3.1.5 on 2021-02-26 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 19, 22, 11, 829062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
